apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-backend
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-backend
  template:
    metadata:
      labels:
        app: ims-backend
    spec:
      containers:
        - name: backend
          # If using minikube, build image inside minikube with the same name/tag
          image: inventory-management-system-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.inventory.svc.cluster.local:3306/Product?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ims-backend
  namespace: inventory
spec:
  selector:
    app: ims-backend
  ports:
    - port: 8080
      targetPort: 8080


